# --- No-secrets / defaults versionados aquí ---
- key: MACD_SIGMA_K
  value: "0.25"      # antes 0.30 → más sensible
- key: MACD_SIGMA_K_TEND
  value: "0.15"      # antes 0.20 → más sensible con tendencia
- key: PENDIENTE_UMBRAL_REL
  value: "0.0004"    # igual

# Habilitadores y parámetros de compra parcial
- key: PERMITIR_COMPRA_CASI_CRUCE
  value: "true"
- key: PERMITIR_COMPRA_DIP
  value: "true"
- key: DIP_PCT
  value: "2.5"       # antes 4.0 → detecta dips más chicos
- key: DIP_LOOKBACK_PUNTOS
  value: "24"
- key: ZSCORE_DIP
  value: "-1.2"      # antes -1.5 → activa dip antes
- key: COMPRA_PARCIAL_PCT
  value: "0.25"
- key: ZSCORE_TAKEPROFIT
  value: "1.2"       # antes 1.5 → TP parcial más temprano
