services:
  - type: web
    name: monitor-criptos
    env: python
    buildCommand: "pip install -r requirements.txt"
    startCommand: "gunicorn monitor_criptos:app"
    envVars:
      - key: TELEGRAM_TOKEN
        sync: false
      - key: TELEGRAM_CHAT_ID
        sync: false
      - key: ENVIAR_RESUMEN_DIARIO
        value: "true"
      - key: RESUMEN_HORA
        value: "09:30"
