services:
  - type: web
    name: chechu-cripto-bot
    runtime: python
    buildCommand: pip install -r requirements.txt
    startCommand: python monitor_criptos.py
    envVars:
      - key: PYTHON_VERSION
        value: 3.10.13
