services:
  - type: web
    name: monitor-criptos
    env: python
    buildCommand: "pip install -r requirements.txt"
    startCommand: "gunicorn wsgi:application"
    envVars:
      # --- Secrets: se definen SOLO en el panel (no aquí) ---
      - key: TELEGRAM_BOT_TOKEN
        sync: false
      - key: TELEGRAM_CHAT_ID
        sync: false
      - key: SUPABASE_URL
        sync: false
      - key: SUPABASE_KEY
        sync: false
      - key: COINMARKETCAP_API_KEY
        sync: false

      # --- No-secrets / defaults versionados aquí ---
      - key: MACD_SIGMA_K
        value: "0.30"
      - key: MACD_SIGMA_K_TEND
        value: "0.20"
      - key: PENDIENTE_UMBRAL_REL
        value: "0.0004"

      # Habilitadores y parámetros de compra parcial
      - key: PERMITIR_COMPRA_CASI_CRUCE
        value: "true"
      - key: PERMITIR_COMPRA_DIP
        value: "true"
      - key: DIP_PCT
        value: "4.0"                # caída mínima % vs. máximo ventana
      - key: DIP_LOOKBACK_PUNTOS
        value: "24"                 # puntos para buscar máximo (≈ muestras)
      - key: ZSCORE_DIP
        value: "-1.5"               # sobre-extensión bajista
      - key: COMPRA_PARCIAL_PCT
        value: "0.25"               # 25% del tamaño “normal”
      - key: ZSCORE_TAKEPROFIT
        value: "1.5"                # (opcional) tp parcial por sobre-extensión
